export const lowEdition = [
	{
		title: '流量时长',
		main: '1000分钟',
	},
	{
		title: '流量单价',
		main: '0.06',
	},
	{
		title: '媒体库',
		main: '100GB',
	},
	{
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '限一个',
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
]
export const highEdition = [
	{
		title: '流量时长',
		main: '1000分钟',
	},
	{
		title: '流量单价',
		main: '0.06',
	},
	{
		title: '媒体库',
		main: '100GB',
	},
	{
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '限一个',
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/correct.png'),
	},
	{
		title: '流量时长',
		titleList: { title1:'频道管理', title2:'频道创建' },
		main: '1000分钟',
		imgURL: require('@/assets/error.png'),
	},
]
